# Generated by Django 6.0.2 on 2026-02-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_rooms_category_rooms_floor_rooms_has_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='permAddress',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
