# Generated by Django 6.0.2 on 2026-03-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_seed_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
